=== ausspeedruns/asm-graphics/configschema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"type": "string"
		},
		"obs": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"autoConnect": {
					"type": "boolean",
					"default": false
				},
				"port": {
					"type": "number",
					"default": 4444
				},
				"ip": {
					"type": "string",
					"default": "localhost"
				},
				"password": {
					"type": "string"
				},
				"customTransitionsFolder": {
					"type": "string"
				}
			}
		},
		"tiltify": {
			"type": "object",
			"description": "Reads incentive data off the website",
			"additionalProperties": false,
			"properties": {
				"autoConnect": {
					"type": "boolean",
					"default": false
				},
				"key": {
					"type": "string",
					"default": ""
				},
				"id": {
					"type": "string",
					"default": ""
				},
				"campaign": {
					"type": "string",
					"default": ""
				}
			}
		},
		"graphql": {
			"type": "object",
			"description": "Reads incentive data off the website",
			"additionalProperties": false,
			"properties": {
				"url": {
					"type": "string",
					"default": ""
				},
				"event": {
					"type": "string",
					"default": ""
				},
				"apiKey": {
					"type": "string",
					"default": ""
				}
			}
		},
		"x32": {
			"type": "object",
			"description": "Controls the Behringer X32 and gets audio information",
			"additionalProperties": false,
			"properties": {
				"autoConnect": {
					"type": "boolean",
					"default": false
				},
				"ip": {
					"type": "string",
					"default": ""
				}
			}
		}
	}
}

=== ausspeedruns/asm-graphics/asm-graphics.example.json
{
	"$schema": "../configschema.json",
	"obs": {
		"autoConnect": false,
		"port": 4444,
		"ip": "localhost",
		"password": ""
	},
	"tiltify": {
		"autoConnect": true,
		"key": "<API-KEY-HERE>",
		"id": "<ID-HERE>",
		"campaign": "<CAMPAIGN-HERE>"
	},
	"graphql": {
		"url": "https://keystone.ausspeedruns.com/api/graphql",
		"event": "<EVENT-HERE>",
		"apiKey": "<API-KEY-HERE>"
	},
	"x32": {
		"autoConnect": false,
		"ip": "192.168.1.1"
	}
}
